### ISSUE TITLE
[bug] Action cannot find labeler.yml config file

### ISSUE THREAD

**Issue by johnnywang** [jimschubert/labeler-action#6]
**Describe the bug**
I've set up the workflow, config file, and submitted several PRs to try testing out the action, only to encounter a `"Failed to execute No file named labeler.yml found in .github"` error when the action runs

**To Reproduce**
1. Set up the labeler action (add workflow, add config file)
2. Submit a test PR
3. Notice that the labeler action fails

**Expected behavior**
The correct labels are added

**Screensh
![Screen Shot 2021-12-22 at 22 33 03](https://user-images.githubusercontent.com/938210/147198610-427a4ed5-c24e-413f-a963-12cf2d7ae855.png)
ots**

**Additional context**
My files are set up as follows right now:

`repo/.github/workflows/pr-labeler.yml`
```
name: PR Labeler
on:
  # Note: using `pull_request` instead of `pull_request_target` since we only allow PRs within the same repo (no forks)
  # The latter allows secrets access to forks, but comes with various security risks: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request:
    types: [ opened ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auto Label PR
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

`repo/.github/labeler.yml`
```
enable:
  issues: false
  prs: true

labels:
  'bugfix':
    include:
      - '\[(bug|BUG|bugfix|BUGFIX)\]'
    exclude: [ ]
  'mobile':
    include:
      - '\[((platform-|PLATFORM-)?(mobile|MOBILE))\]'
    exclude: [ ]
  'platform':
    include:
      - '\[((platform|PLATFORM)(-server|-SERVER)?)\]'
    exclude: [ ]
  'web':
    include:
      - '\[(web|WEB|platform-client|PLATFORM-CLIENT)\]'
    exclude: [ ]
```

I definitely see the `labeler.yml` file in the PR, so I'm not sure why this is failing

**Comment by jimschubert** [comment]
Hey, Johnny.

It should be:
```
on:
  pull_request_target:
    types: [opened]
```

You didn't share an example failing PR and your activity history shows as private on your profile. I assume what's happened is you're following a fork/pull model. The `pull_request_target` event works in the context of the original repo and therefore has access to the `GITHUB_TOKEN` variable, whereas `pull_request` works in the context of the contributor's repo. You can only use `pull_request` when opening a PR directly against the origin repo. It's not really a bug, it's just how the events work. I haven't seen anyone using `permissions` with this action but I assume the reason you're getting the specific error message is because the `GITHUB_TOKEN` generated for the fork doesn't have read access to the original/official repo.

Please refer to the [official event docs](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target):
<img width="747" alt="image" src="https://user-images.githubusercontent.com/109659/147398473-bcdf5e0c-ac85-426e-bcdc-0d149c5d68c5.png">

I submitted a request for `pull_request_target` after [posting in the community forum](https://github.community/t/req-allow-users-to-add-labels-to-issues-and-prs-they-author/18174) and a few months later the feature was available. Prior to this, I'd see similar access errors as you're experiencing. If you get stuck you can check out [other repo configs](https://github.com/search?q=jimschubert%2Flabeler-action&type=Code).

On another note since I haven't used the [permissions syntax](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) or seen anyone using it with this action, I'd guess you also need `issues: read|write` since labeling of PRs goes through the issues API. For whatever reason, GitHub API treats issues and PRs both as issues for labeling but not comments. I'd expect after you change to `pull_request_target` you'd then have an error about failing to persist labels.

If you want to temporarily enable debugging in the labeler code, you can also add `LOG_LEVEL: debug`. Fair warning… I don't output a ton of debug logs.

Full recommended config:

```
name: PR Labeler
on:
  pull_request_target:
    types: [ opened ]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read|write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auto Label PR
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          LOG_LEVEL: "debug"
```

Let me know how that works out.
