### ISSUE TITLE
[Question]  How to apply labeling only to PR titles?

### ISSUE THREAD

**Issue by seung-seop-ahn** [jimschubert/labeler-action#9]
**What is your question?**
Is there a way to support only the PR title, excluding the body?

**Where did you look before asking here?**
- README
![스크린샷 2024-04-17 오후 9 52 47](https://github.com/jimschubert/labeler-action/assets/146805966/737093e5-0862-410a-82af-62868950102c)

**Additional context**

**Comment by jimschubert** [comment]
Prep work for this is here https://github.com/jimschubert/labeler/pull/14
I just need to integrate it into the action

**Comment by jimschubert** [comment]
I've finally gotten around to this.

Here's an example schema where you can choose between title and body via the new `fields` list item:

```
# auto-labeler "full" schema

# enable auto-labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

# (Optional): Determine which fields of the issue or pull request to evaluate.
fields:
  - title
  - body

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'bug':
    include:
      - '\bbug[s]?\b'
    exclude: []
```
